/*
 * generated by Xtext 2.41.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SimplepdlUiModule extends AbstractSimplepdlUiModule {

	public SimplepdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
