/*
 * generated by Xtext 2.41.0
 */
package xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimplepdlScopeProvider extends DelegatingScopeProvider {
}
