/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SimplePDLUiModule extends AbstractSimplePDLUiModule {

	public SimplePDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
