/*
 * generated by Xtext 2.41.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalSimplepdlParser;
import xtext.services.SimplepdlGrammarAccess;

public class SimplepdlParser extends AbstractAntlrParser {

	@Inject
	private SimplepdlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimplepdlParser createParser(XtextTokenStream stream) {
		return new InternalSimplepdlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Process";
	}

	public SimplepdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimplepdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
