/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.simplepdl.SimplePDLRuntimeModule;
import org.xtext.simplepdl.SimplePDLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SimplePDLIdeSetup extends SimplePDLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SimplePDLRuntimeModule(), new SimplePDLIdeModule()));
	}
	
}
