/**
 * generated by Xtext 2.41.0
 */
package xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import simplepdl.Guidance;
import simplepdl.Parameter;
import simplepdl.Resource;
import simplepdl.WorkDefinition;
import simplepdl.WorkSequence;
import xtext.services.SimplepdlGrammarAccess;

@SuppressWarnings("all")
public class SimplepdlFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SimplepdlGrammarAccess _simplepdlGrammarAccess;

  protected void _format(final simplepdl.Process process, @Extension final IFormattableDocument document) {
    EList<WorkSequence> _worksequence = process.getWorksequence();
    for (final WorkSequence workSequence : _worksequence) {
      document.<WorkSequence>format(workSequence);
    }
    EList<Guidance> _guidance = process.getGuidance();
    for (final Guidance guidance : _guidance) {
      document.<Guidance>format(guidance);
    }
    EList<Resource> _resource = process.getResource();
    for (final Resource resource : _resource) {
      document.<Resource>format(resource);
    }
    EList<WorkDefinition> _workdefinition = process.getWorkdefinition();
    for (final WorkDefinition workDefinition : _workdefinition) {
      document.<WorkDefinition>format(workDefinition);
    }
  }

  protected void _format(final WorkDefinition workDefinition, @Extension final IFormattableDocument document) {
    EList<Parameter> _parameter = workDefinition.getParameter();
    for (final Parameter parameter : _parameter) {
      document.<Parameter>format(parameter);
    }
  }

  @XbaseGenerated
  public void format(final Object process, final IFormattableDocument document) {
    if (process instanceof XtextResource) {
      _format((XtextResource)process, document);
      return;
    } else if (process instanceof simplepdl.Process) {
      _format((simplepdl.Process)process, document);
      return;
    } else if (process instanceof WorkDefinition) {
      _format((WorkDefinition)process, document);
      return;
    } else if (process instanceof EObject) {
      _format((EObject)process, document);
      return;
    } else if (process == null) {
      _format((Void)null, document);
      return;
    } else if (process != null) {
      _format(process, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(process, document).toString());
    }
  }
}
