/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.simplepdl.ui.internal.SimplepdlActivator;

public class SimplePDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SimplepdlActivator.getInstance().getInjector("org.xtext.simplepdl.SimplePDL");
	}

}
