/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.simplepdl.ui.internal.SimplepdlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimplePDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SimplepdlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SimplepdlActivator activator = SimplepdlActivator.getInstance();
		return activator != null ? activator.getInjector(SimplepdlActivator.ORG_XTEXT_SIMPLEPDL_SIMPLEPDL) : null;
	}

}
