/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.simplepdl.ide.contentassist.antlr.internal.InternalSimplePDLParser;
import org.xtext.simplepdl.services.SimplePDLGrammarAccess;

public class SimplePDLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SimplePDLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SimplePDLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getWorkSequenceTypeAccess().getAlternatives(), "rule__WorkSequenceType__Alternatives");
			builder.put(grammarAccess.getProcessAccess().getGroup(), "rule__Process__Group__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_3(), "rule__Process__Group_3__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_3_3(), "rule__Process__Group_3_3__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_4(), "rule__Process__Group_4__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_4_3(), "rule__Process__Group_4_3__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_5(), "rule__Process__Group_5__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_5_3(), "rule__Process__Group_5_3__0");
			builder.put(grammarAccess.getProcessAccess().getGroup_9(), "rule__Process__Group_9__0");
			builder.put(grammarAccess.getWorkSequenceAccess().getGroup(), "rule__WorkSequence__Group__0");
			builder.put(grammarAccess.getWorkSequenceAccess().getGroup_2(), "rule__WorkSequence__Group_2__0");
			builder.put(grammarAccess.getGuidanceAccess().getGroup(), "rule__Guidance__Group__0");
			builder.put(grammarAccess.getGuidanceAccess().getGroup_3(), "rule__Guidance__Group_3__0");
			builder.put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGroup(), "rule__WorkDefinition__Group__0");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGroup_4(), "rule__WorkDefinition__Group_4__0");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGroup_5(), "rule__WorkDefinition__Group_5__0");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGroup_6(), "rule__WorkDefinition__Group_6__0");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGroup_6_3(), "rule__WorkDefinition__Group_6_3__0");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGroup_7(), "rule__WorkDefinition__Group_7__0");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGroup_7_3(), "rule__WorkDefinition__Group_7_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getProcessAccess().getNameAssignment_1(), "rule__Process__NameAssignment_1");
			builder.put(grammarAccess.getProcessAccess().getWorksequenceAssignment_3_2(), "rule__Process__WorksequenceAssignment_3_2");
			builder.put(grammarAccess.getProcessAccess().getWorksequenceAssignment_3_3_1(), "rule__Process__WorksequenceAssignment_3_3_1");
			builder.put(grammarAccess.getProcessAccess().getGuidanceAssignment_4_2(), "rule__Process__GuidanceAssignment_4_2");
			builder.put(grammarAccess.getProcessAccess().getGuidanceAssignment_4_3_1(), "rule__Process__GuidanceAssignment_4_3_1");
			builder.put(grammarAccess.getProcessAccess().getResourceAssignment_5_2(), "rule__Process__ResourceAssignment_5_2");
			builder.put(grammarAccess.getProcessAccess().getResourceAssignment_5_3_1(), "rule__Process__ResourceAssignment_5_3_1");
			builder.put(grammarAccess.getProcessAccess().getWorkdefinitionAssignment_8(), "rule__Process__WorkdefinitionAssignment_8");
			builder.put(grammarAccess.getProcessAccess().getWorkdefinitionAssignment_9_1(), "rule__Process__WorkdefinitionAssignment_9_1");
			builder.put(grammarAccess.getWorkSequenceAccess().getLinkTypeAssignment_2_1(), "rule__WorkSequence__LinkTypeAssignment_2_1");
			builder.put(grammarAccess.getWorkSequenceAccess().getPredecessorAssignment_4(), "rule__WorkSequence__PredecessorAssignment_4");
			builder.put(grammarAccess.getWorkSequenceAccess().getSuccessorAssignment_6(), "rule__WorkSequence__SuccessorAssignment_6");
			builder.put(grammarAccess.getGuidanceAccess().getDescriptionAssignment_3_1(), "rule__Guidance__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getResourceAccess().getNameAssignment_1(), "rule__Resource__NameAssignment_1");
			builder.put(grammarAccess.getResourceAccess().getOccuranceNoAssignment_4(), "rule__Resource__OccuranceNoAssignment_4");
			builder.put(grammarAccess.getWorkDefinitionAccess().getNameAssignment_2(), "rule__WorkDefinition__NameAssignment_2");
			builder.put(grammarAccess.getWorkDefinitionAccess().getLinksToSuccessorsAssignment_4_1(), "rule__WorkDefinition__LinksToSuccessorsAssignment_4_1");
			builder.put(grammarAccess.getWorkDefinitionAccess().getLinksToPredecessorsAssignment_5_1(), "rule__WorkDefinition__LinksToPredecessorsAssignment_5_1");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGuidanceAssignment_6_2(), "rule__WorkDefinition__GuidanceAssignment_6_2");
			builder.put(grammarAccess.getWorkDefinitionAccess().getGuidanceAssignment_6_3_1(), "rule__WorkDefinition__GuidanceAssignment_6_3_1");
			builder.put(grammarAccess.getWorkDefinitionAccess().getParameterAssignment_7_2(), "rule__WorkDefinition__ParameterAssignment_7_2");
			builder.put(grammarAccess.getWorkDefinitionAccess().getParameterAssignment_7_3_1(), "rule__WorkDefinition__ParameterAssignment_7_3_1");
			builder.put(grammarAccess.getParameterAccess().getQuantityAssignment_3(), "rule__Parameter__QuantityAssignment_3");
			builder.put(grammarAccess.getParameterAccess().getResourceAssignment_5(), "rule__Parameter__ResourceAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SimplePDLGrammarAccess grammarAccess;

	@Override
	protected InternalSimplePDLParser createParser() {
		InternalSimplePDLParser result = new InternalSimplePDLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SimplePDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimplePDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
