/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.simplepdl.services.SimplePDLGrammarAccess;
import simplePDL.Guidance;
import simplePDL.Resource;
import simplePDL.SimplePDLPackage;
import simplePDL.WorkDefinition;
import simplePDL.WorkSequence;

@SuppressWarnings("all")
public class SimplePDLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SimplePDLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SimplePDLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SimplePDLPackage.GUIDANCE:
				sequence_Guidance(context, (Guidance) semanticObject); 
				return; 
			case SimplePDLPackage.PARAMETER:
				sequence_Parameter(context, (simplePDL.Parameter) semanticObject); 
				return; 
			case SimplePDLPackage.PROCESS:
				sequence_Process(context, (simplePDL.Process) semanticObject); 
				return; 
			case SimplePDLPackage.RESOURCE:
				sequence_Resource(context, (Resource) semanticObject); 
				return; 
			case SimplePDLPackage.WORK_DEFINITION:
				sequence_WorkDefinition(context, (WorkDefinition) semanticObject); 
				return; 
			case SimplePDLPackage.WORK_SEQUENCE:
				sequence_WorkSequence(context, (WorkSequence) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Guidance returns Guidance
	 *
	 * Constraint:
	 *     description=EString?
	 * </pre>
	 */
	protected void sequence_Guidance(ISerializationContext context, Guidance semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Parameter returns Parameter
	 *
	 * Constraint:
	 *     (quantity=EInt resource=[Resource|EString])
	 * </pre>
	 */
	protected void sequence_Parameter(ISerializationContext context, simplePDL.Parameter semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SimplePDLPackage.Literals.PARAMETER__QUANTITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SimplePDLPackage.Literals.PARAMETER__QUANTITY));
			if (transientValues.isValueTransient(semanticObject, SimplePDLPackage.Literals.PARAMETER__RESOURCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SimplePDLPackage.Literals.PARAMETER__RESOURCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParameterAccess().getQuantityEIntParserRuleCall_3_0(), semanticObject.getQuantity());
		feeder.accept(grammarAccess.getParameterAccess().getResourceResourceEStringParserRuleCall_5_0_1(), semanticObject.eGet(SimplePDLPackage.Literals.PARAMETER__RESOURCE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Process returns Process
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (worksequence+=WorkSequence worksequence+=WorkSequence*)? 
	 *         (guidance+=Guidance guidance+=Guidance*)? 
	 *         (resource+=Resource resource+=Resource*)? 
	 *         workdefinition+=WorkDefinition 
	 *         workdefinition+=WorkDefinition*
	 *     )
	 * </pre>
	 */
	protected void sequence_Process(ISerializationContext context, simplePDL.Process semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Resource returns Resource
	 *
	 * Constraint:
	 *     (name=EString occuranceNo=EInt)
	 * </pre>
	 */
	protected void sequence_Resource(ISerializationContext context, Resource semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SimplePDLPackage.Literals.RESOURCE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SimplePDLPackage.Literals.RESOURCE__NAME));
			if (transientValues.isValueTransient(semanticObject, SimplePDLPackage.Literals.RESOURCE__OCCURANCE_NO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SimplePDLPackage.Literals.RESOURCE__OCCURANCE_NO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getResourceAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getResourceAccess().getOccuranceNoEIntParserRuleCall_4_0(), semanticObject.getOccuranceNo());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     WorkDefinition returns WorkDefinition
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         linksToSuccessors=[WorkSequence|EString]? 
	 *         linksToPredecessors=[WorkSequence|EString]? 
	 *         (guidance+=[Guidance|EString] guidance+=[Guidance|EString]*)? 
	 *         (parameter+=Parameter parameter+=Parameter*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_WorkDefinition(ISerializationContext context, WorkDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     WorkSequence returns WorkSequence
	 *
	 * Constraint:
	 *     (linkType=WorkSequenceType? predecessor=[WorkDefinition|EString] successor=[WorkDefinition|EString])
	 * </pre>
	 */
	protected void sequence_WorkSequence(ISerializationContext context, WorkSequence semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
