/*
 * generated by Xtext 2.41.0
 */
package xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.SimplepdlRuntimeModule;
import xtext.SimplepdlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SimplepdlIdeSetup extends SimplepdlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SimplepdlRuntimeModule(), new SimplepdlIdeModule()));
	}
	
}
