/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SimplePDLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cWorksequenceKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cWorksequenceAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cWorksequenceWorkSequenceParserRuleCall_3_2_0 = (RuleCall)cWorksequenceAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cWorksequenceAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cWorksequenceWorkSequenceParserRuleCall_3_3_1_0 = (RuleCall)cWorksequenceAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cGuidanceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cGuidanceAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cGuidanceGuidanceParserRuleCall_4_2_0 = (RuleCall)cGuidanceAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cGuidanceAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cGuidanceGuidanceParserRuleCall_4_3_1_0 = (RuleCall)cGuidanceAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cResourceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cResourceAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cResourceResourceParserRuleCall_5_2_0 = (RuleCall)cResourceAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cResourceAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cResourceResourceParserRuleCall_5_3_1_0 = (RuleCall)cResourceAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cWorkdefinitionKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cWorkdefinitionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cWorkdefinitionWorkDefinitionParserRuleCall_8_0 = (RuleCall)cWorkdefinitionAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cWorkdefinitionAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cWorkdefinitionWorkDefinitionParserRuleCall_9_1_0 = (RuleCall)cWorkdefinitionAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Process returns Process:
		//    'Process'
		//    name=EString
		//    '{'
		//        ('worksequence' '{' worksequence+=WorkSequence ( "," worksequence+=WorkSequence)* '}' )?
		//        ('guidance' '{' guidance+=Guidance ( "," guidance+=Guidance)* '}' )?
		//        ('resource' '{' resource+=Resource ( "," resource+=Resource)* '}' )?
		//        'workdefinition' '{' workdefinition+=WorkDefinition ( "," workdefinition+=WorkDefinition)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Process'
		//name=EString
		//'{'
		//    ('worksequence' '{' worksequence+=WorkSequence ( "," worksequence+=WorkSequence)* '}' )?
		//    ('guidance' '{' guidance+=Guidance ( "," guidance+=Guidance)* '}' )?
		//    ('resource' '{' resource+=Resource ( "," resource+=Resource)* '}' )?
		//    'workdefinition' '{' workdefinition+=WorkDefinition ( "," workdefinition+=WorkDefinition)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Process'
		public Keyword getProcessKeyword_0() { return cProcessKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('worksequence' '{' worksequence+=WorkSequence ( "," worksequence+=WorkSequence)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'worksequence'
		public Keyword getWorksequenceKeyword_3_0() { return cWorksequenceKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//worksequence+=WorkSequence
		public Assignment getWorksequenceAssignment_3_2() { return cWorksequenceAssignment_3_2; }
		
		//WorkSequence
		public RuleCall getWorksequenceWorkSequenceParserRuleCall_3_2_0() { return cWorksequenceWorkSequenceParserRuleCall_3_2_0; }
		
		//( "," worksequence+=WorkSequence)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//worksequence+=WorkSequence
		public Assignment getWorksequenceAssignment_3_3_1() { return cWorksequenceAssignment_3_3_1; }
		
		//WorkSequence
		public RuleCall getWorksequenceWorkSequenceParserRuleCall_3_3_1_0() { return cWorksequenceWorkSequenceParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('guidance' '{' guidance+=Guidance ( "," guidance+=Guidance)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'guidance'
		public Keyword getGuidanceKeyword_4_0() { return cGuidanceKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//guidance+=Guidance
		public Assignment getGuidanceAssignment_4_2() { return cGuidanceAssignment_4_2; }
		
		//Guidance
		public RuleCall getGuidanceGuidanceParserRuleCall_4_2_0() { return cGuidanceGuidanceParserRuleCall_4_2_0; }
		
		//( "," guidance+=Guidance)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//guidance+=Guidance
		public Assignment getGuidanceAssignment_4_3_1() { return cGuidanceAssignment_4_3_1; }
		
		//Guidance
		public RuleCall getGuidanceGuidanceParserRuleCall_4_3_1_0() { return cGuidanceGuidanceParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('resource' '{' resource+=Resource ( "," resource+=Resource)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'resource'
		public Keyword getResourceKeyword_5_0() { return cResourceKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//resource+=Resource
		public Assignment getResourceAssignment_5_2() { return cResourceAssignment_5_2; }
		
		//Resource
		public RuleCall getResourceResourceParserRuleCall_5_2_0() { return cResourceResourceParserRuleCall_5_2_0; }
		
		//( "," resource+=Resource)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//resource+=Resource
		public Assignment getResourceAssignment_5_3_1() { return cResourceAssignment_5_3_1; }
		
		//Resource
		public RuleCall getResourceResourceParserRuleCall_5_3_1_0() { return cResourceResourceParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'workdefinition'
		public Keyword getWorkdefinitionKeyword_6() { return cWorkdefinitionKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//workdefinition+=WorkDefinition
		public Assignment getWorkdefinitionAssignment_8() { return cWorkdefinitionAssignment_8; }
		
		//WorkDefinition
		public RuleCall getWorkdefinitionWorkDefinitionParserRuleCall_8_0() { return cWorkdefinitionWorkDefinitionParserRuleCall_8_0; }
		
		//( "," workdefinition+=WorkDefinition)*
		public Group getGroup_9() { return cGroup_9; }
		
		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }
		
		//workdefinition+=WorkDefinition
		public Assignment getWorkdefinitionAssignment_9_1() { return cWorkdefinitionAssignment_9_1; }
		
		//WorkDefinition
		public RuleCall getWorkdefinitionWorkDefinitionParserRuleCall_9_1_0() { return cWorkdefinitionWorkDefinitionParserRuleCall_9_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class WorkSequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.WorkSequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWorkSequenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLinkTypeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cLinkTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLinkTypeWorkSequenceTypeEnumRuleCall_2_1_0 = (RuleCall)cLinkTypeAssignment_2_1.eContents().get(0);
		private final Keyword cPredecessorKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPredecessorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cPredecessorWorkDefinitionCrossReference_4_0 = (CrossReference)cPredecessorAssignment_4.eContents().get(0);
		private final RuleCall cPredecessorWorkDefinitionEStringParserRuleCall_4_0_1 = (RuleCall)cPredecessorWorkDefinitionCrossReference_4_0.eContents().get(1);
		private final Keyword cSuccessorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSuccessorAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSuccessorWorkDefinitionCrossReference_6_0 = (CrossReference)cSuccessorAssignment_6.eContents().get(0);
		private final RuleCall cSuccessorWorkDefinitionEStringParserRuleCall_6_0_1 = (RuleCall)cSuccessorWorkDefinitionCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//WorkSequence returns WorkSequence:
		//    'WorkSequence'
		//    '{'
		//        ('linkType' linkType=WorkSequenceType)?
		//        'predecessor' predecessor=[WorkDefinition|EString]
		//        'successor' successor=[WorkDefinition|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'WorkSequence'
		//'{'
		//    ('linkType' linkType=WorkSequenceType)?
		//    'predecessor' predecessor=[WorkDefinition|EString]
		//    'successor' successor=[WorkDefinition|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'WorkSequence'
		public Keyword getWorkSequenceKeyword_0() { return cWorkSequenceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('linkType' linkType=WorkSequenceType)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'linkType'
		public Keyword getLinkTypeKeyword_2_0() { return cLinkTypeKeyword_2_0; }
		
		//linkType=WorkSequenceType
		public Assignment getLinkTypeAssignment_2_1() { return cLinkTypeAssignment_2_1; }
		
		//WorkSequenceType
		public RuleCall getLinkTypeWorkSequenceTypeEnumRuleCall_2_1_0() { return cLinkTypeWorkSequenceTypeEnumRuleCall_2_1_0; }
		
		//'predecessor'
		public Keyword getPredecessorKeyword_3() { return cPredecessorKeyword_3; }
		
		//predecessor=[WorkDefinition|EString]
		public Assignment getPredecessorAssignment_4() { return cPredecessorAssignment_4; }
		
		//[WorkDefinition|EString]
		public CrossReference getPredecessorWorkDefinitionCrossReference_4_0() { return cPredecessorWorkDefinitionCrossReference_4_0; }
		
		//EString
		public RuleCall getPredecessorWorkDefinitionEStringParserRuleCall_4_0_1() { return cPredecessorWorkDefinitionEStringParserRuleCall_4_0_1; }
		
		//'successor'
		public Keyword getSuccessorKeyword_5() { return cSuccessorKeyword_5; }
		
		//successor=[WorkDefinition|EString]
		public Assignment getSuccessorAssignment_6() { return cSuccessorAssignment_6; }
		
		//[WorkDefinition|EString]
		public CrossReference getSuccessorWorkDefinitionCrossReference_6_0() { return cSuccessorWorkDefinitionCrossReference_6_0; }
		
		//EString
		public RuleCall getSuccessorWorkDefinitionEStringParserRuleCall_6_0_1() { return cSuccessorWorkDefinitionEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class GuidanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.Guidance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGuidanceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGuidanceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Guidance returns Guidance:
		//    {Guidance}
		//    'Guidance'
		//    '{'
		//        ('description' description=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Guidance}
		//'Guidance'
		//'{'
		//    ('description' description=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Guidance}
		public Action getGuidanceAction_0() { return cGuidanceAction_0; }
		
		//'Guidance'
		public Keyword getGuidanceKeyword_1() { return cGuidanceKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cOccuranceNoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cOccuranceNoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOccuranceNoEIntParserRuleCall_4_0 = (RuleCall)cOccuranceNoAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Resource returns Resource:
		//    'Resource'
		//    name=EString
		//    '{'
		//        'occuranceNo' occuranceNo=EInt
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Resource'
		//name=EString
		//'{'
		//    'occuranceNo' occuranceNo=EInt
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Resource'
		public Keyword getResourceKeyword_0() { return cResourceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'occuranceNo'
		public Keyword getOccuranceNoKeyword_3() { return cOccuranceNoKeyword_3; }
		
		//occuranceNo=EInt
		public Assignment getOccuranceNoAssignment_4() { return cOccuranceNoAssignment_4; }
		
		//EInt
		public RuleCall getOccuranceNoEIntParserRuleCall_4_0() { return cOccuranceNoEIntParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class WorkDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.WorkDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWorkDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cWorkDefinitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLinksToSuccessorsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLinksToSuccessorsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cLinksToSuccessorsWorkSequenceCrossReference_4_1_0 = (CrossReference)cLinksToSuccessorsAssignment_4_1.eContents().get(0);
		private final RuleCall cLinksToSuccessorsWorkSequenceEStringParserRuleCall_4_1_0_1 = (RuleCall)cLinksToSuccessorsWorkSequenceCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLinksToPredecessorsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLinksToPredecessorsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cLinksToPredecessorsWorkSequenceCrossReference_5_1_0 = (CrossReference)cLinksToPredecessorsAssignment_5_1.eContents().get(0);
		private final RuleCall cLinksToPredecessorsWorkSequenceEStringParserRuleCall_5_1_0_1 = (RuleCall)cLinksToPredecessorsWorkSequenceCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cGuidanceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cGuidanceAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cGuidanceGuidanceCrossReference_6_2_0 = (CrossReference)cGuidanceAssignment_6_2.eContents().get(0);
		private final RuleCall cGuidanceGuidanceEStringParserRuleCall_6_2_0_1 = (RuleCall)cGuidanceGuidanceCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cGuidanceAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cGuidanceGuidanceCrossReference_6_3_1_0 = (CrossReference)cGuidanceAssignment_6_3_1.eContents().get(0);
		private final RuleCall cGuidanceGuidanceEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cGuidanceGuidanceCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParameterKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParameterAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParameterParameterParserRuleCall_7_2_0 = (RuleCall)cParameterAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParameterAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParameterParameterParserRuleCall_7_3_1_0 = (RuleCall)cParameterAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//WorkDefinition returns WorkDefinition:
		//    {WorkDefinition}
		//    'WorkDefinition'
		//    name=EString
		//    '{'
		//        ('linksToSuccessors' linksToSuccessors=[WorkSequence|EString])?
		//        ('linksToPredecessors' linksToPredecessors=[WorkSequence|EString])?
		//        ('guidance' '(' guidance+=[Guidance|EString] ( "," guidance+=[Guidance|EString])* ')' )?
		//        ('parameter' '{' parameter+=Parameter ( "," parameter+=Parameter)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{WorkDefinition}
		//'WorkDefinition'
		//name=EString
		//'{'
		//    ('linksToSuccessors' linksToSuccessors=[WorkSequence|EString])?
		//    ('linksToPredecessors' linksToPredecessors=[WorkSequence|EString])?
		//    ('guidance' '(' guidance+=[Guidance|EString] ( "," guidance+=[Guidance|EString])* ')' )?
		//    ('parameter' '{' parameter+=Parameter ( "," parameter+=Parameter)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{WorkDefinition}
		public Action getWorkDefinitionAction_0() { return cWorkDefinitionAction_0; }
		
		//'WorkDefinition'
		public Keyword getWorkDefinitionKeyword_1() { return cWorkDefinitionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('linksToSuccessors' linksToSuccessors=[WorkSequence|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'linksToSuccessors'
		public Keyword getLinksToSuccessorsKeyword_4_0() { return cLinksToSuccessorsKeyword_4_0; }
		
		//linksToSuccessors=[WorkSequence|EString]
		public Assignment getLinksToSuccessorsAssignment_4_1() { return cLinksToSuccessorsAssignment_4_1; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToSuccessorsWorkSequenceCrossReference_4_1_0() { return cLinksToSuccessorsWorkSequenceCrossReference_4_1_0; }
		
		//EString
		public RuleCall getLinksToSuccessorsWorkSequenceEStringParserRuleCall_4_1_0_1() { return cLinksToSuccessorsWorkSequenceEStringParserRuleCall_4_1_0_1; }
		
		//('linksToPredecessors' linksToPredecessors=[WorkSequence|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'linksToPredecessors'
		public Keyword getLinksToPredecessorsKeyword_5_0() { return cLinksToPredecessorsKeyword_5_0; }
		
		//linksToPredecessors=[WorkSequence|EString]
		public Assignment getLinksToPredecessorsAssignment_5_1() { return cLinksToPredecessorsAssignment_5_1; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToPredecessorsWorkSequenceCrossReference_5_1_0() { return cLinksToPredecessorsWorkSequenceCrossReference_5_1_0; }
		
		//EString
		public RuleCall getLinksToPredecessorsWorkSequenceEStringParserRuleCall_5_1_0_1() { return cLinksToPredecessorsWorkSequenceEStringParserRuleCall_5_1_0_1; }
		
		//('guidance' '(' guidance+=[Guidance|EString] ( "," guidance+=[Guidance|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'guidance'
		public Keyword getGuidanceKeyword_6_0() { return cGuidanceKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//guidance+=[Guidance|EString]
		public Assignment getGuidanceAssignment_6_2() { return cGuidanceAssignment_6_2; }
		
		//[Guidance|EString]
		public CrossReference getGuidanceGuidanceCrossReference_6_2_0() { return cGuidanceGuidanceCrossReference_6_2_0; }
		
		//EString
		public RuleCall getGuidanceGuidanceEStringParserRuleCall_6_2_0_1() { return cGuidanceGuidanceEStringParserRuleCall_6_2_0_1; }
		
		//( "," guidance+=[Guidance|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//guidance+=[Guidance|EString]
		public Assignment getGuidanceAssignment_6_3_1() { return cGuidanceAssignment_6_3_1; }
		
		//[Guidance|EString]
		public CrossReference getGuidanceGuidanceCrossReference_6_3_1_0() { return cGuidanceGuidanceCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getGuidanceGuidanceEStringParserRuleCall_6_3_1_0_1() { return cGuidanceGuidanceEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('parameter' '{' parameter+=Parameter ( "," parameter+=Parameter)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameter'
		public Keyword getParameterKeyword_7_0() { return cParameterKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameter+=Parameter
		public Assignment getParameterAssignment_7_2() { return cParameterAssignment_7_2; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_7_2_0() { return cParameterParameterParserRuleCall_7_2_0; }
		
		//( "," parameter+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameter+=Parameter
		public Assignment getParameterAssignment_7_3_1() { return cParameterAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_7_3_1_0() { return cParameterParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParameterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cQuantityKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cQuantityAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQuantityEIntParserRuleCall_3_0 = (RuleCall)cQuantityAssignment_3.eContents().get(0);
		private final Keyword cResourceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cResourceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cResourceResourceCrossReference_5_0 = (CrossReference)cResourceAssignment_5.eContents().get(0);
		private final RuleCall cResourceResourceEStringParserRuleCall_5_0_1 = (RuleCall)cResourceResourceCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Parameter returns Parameter:
		//    'Parameter'
		//    '{'
		//        'quantity' quantity=EInt
		//        'resource' resource=[Resource|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Parameter'
		//'{'
		//    'quantity' quantity=EInt
		//    'resource' resource=[Resource|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Parameter'
		public Keyword getParameterKeyword_0() { return cParameterKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'quantity'
		public Keyword getQuantityKeyword_2() { return cQuantityKeyword_2; }
		
		//quantity=EInt
		public Assignment getQuantityAssignment_3() { return cQuantityAssignment_3; }
		
		//EInt
		public RuleCall getQuantityEIntParserRuleCall_3_0() { return cQuantityEIntParserRuleCall_3_0; }
		
		//'resource'
		public Keyword getResourceKeyword_4() { return cResourceKeyword_4; }
		
		//resource=[Resource|EString]
		public Assignment getResourceAssignment_5() { return cResourceAssignment_5; }
		
		//[Resource|EString]
		public CrossReference getResourceResourceCrossReference_5_0() { return cResourceResourceCrossReference_5_0; }
		
		//EString
		public RuleCall getResourceResourceEStringParserRuleCall_5_0_1() { return cResourceResourceEStringParserRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	public class WorkSequenceTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.simplepdl.SimplePDL.WorkSequenceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStartToStartEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStartToStartStartToStartKeyword_0_0 = (Keyword)cStartToStartEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFinishToStartEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFinishToStartFinishToStartKeyword_1_0 = (Keyword)cFinishToStartEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStartToFinishEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStartToFinishStartToFinishKeyword_2_0 = (Keyword)cStartToFinishEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFinishToFinishEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFinishToFinishFinishToFinishKeyword_3_0 = (Keyword)cFinishToFinishEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum WorkSequenceType returns WorkSequenceType:
		//                startToStart = 'startToStart' | finishToStart = 'finishToStart' | startToFinish = 'startToFinish' | finishToFinish = 'finishToFinish';
		public EnumRule getRule() { return rule; }
		
		//startToStart = 'startToStart' | finishToStart = 'finishToStart' | startToFinish = 'startToFinish' | finishToFinish = 'finishToFinish'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//startToStart = 'startToStart'
		public EnumLiteralDeclaration getStartToStartEnumLiteralDeclaration_0() { return cStartToStartEnumLiteralDeclaration_0; }
		
		//'startToStart'
		public Keyword getStartToStartStartToStartKeyword_0_0() { return cStartToStartStartToStartKeyword_0_0; }
		
		//finishToStart = 'finishToStart'
		public EnumLiteralDeclaration getFinishToStartEnumLiteralDeclaration_1() { return cFinishToStartEnumLiteralDeclaration_1; }
		
		//'finishToStart'
		public Keyword getFinishToStartFinishToStartKeyword_1_0() { return cFinishToStartFinishToStartKeyword_1_0; }
		
		//startToFinish = 'startToFinish'
		public EnumLiteralDeclaration getStartToFinishEnumLiteralDeclaration_2() { return cStartToFinishEnumLiteralDeclaration_2; }
		
		//'startToFinish'
		public Keyword getStartToFinishStartToFinishKeyword_2_0() { return cStartToFinishStartToFinishKeyword_2_0; }
		
		//finishToFinish = 'finishToFinish'
		public EnumLiteralDeclaration getFinishToFinishEnumLiteralDeclaration_3() { return cFinishToFinishEnumLiteralDeclaration_3; }
		
		//'finishToFinish'
		public Keyword getFinishToFinishFinishToFinishKeyword_3_0() { return cFinishToFinishFinishToFinishKeyword_3_0; }
	}
	
	private final ProcessElements pProcess;
	private final EStringElements pEString;
	private final WorkSequenceElements pWorkSequence;
	private final GuidanceElements pGuidance;
	private final ResourceElements pResource;
	private final WorkDefinitionElements pWorkDefinition;
	private final WorkSequenceTypeElements eWorkSequenceType;
	private final EIntElements pEInt;
	private final ParameterElements pParameter;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SimplePDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProcess = new ProcessElements();
		this.pEString = new EStringElements();
		this.pWorkSequence = new WorkSequenceElements();
		this.pGuidance = new GuidanceElements();
		this.pResource = new ResourceElements();
		this.pWorkDefinition = new WorkDefinitionElements();
		this.eWorkSequenceType = new WorkSequenceTypeElements();
		this.pEInt = new EIntElements();
		this.pParameter = new ParameterElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.simplepdl.SimplePDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Process returns Process:
	//    'Process'
	//    name=EString
	//    '{'
	//        ('worksequence' '{' worksequence+=WorkSequence ( "," worksequence+=WorkSequence)* '}' )?
	//        ('guidance' '{' guidance+=Guidance ( "," guidance+=Guidance)* '}' )?
	//        ('resource' '{' resource+=Resource ( "," resource+=Resource)* '}' )?
	//        'workdefinition' '{' workdefinition+=WorkDefinition ( "," workdefinition+=WorkDefinition)* '}'
	//    '}';
	public ProcessElements getProcessAccess() {
		return pProcess;
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//WorkSequence returns WorkSequence:
	//    'WorkSequence'
	//    '{'
	//        ('linkType' linkType=WorkSequenceType)?
	//        'predecessor' predecessor=[WorkDefinition|EString]
	//        'successor' successor=[WorkDefinition|EString]
	//    '}';
	public WorkSequenceElements getWorkSequenceAccess() {
		return pWorkSequence;
	}
	
	public ParserRule getWorkSequenceRule() {
		return getWorkSequenceAccess().getRule();
	}
	
	//Guidance returns Guidance:
	//    {Guidance}
	//    'Guidance'
	//    '{'
	//        ('description' description=EString)?
	//    '}';
	public GuidanceElements getGuidanceAccess() {
		return pGuidance;
	}
	
	public ParserRule getGuidanceRule() {
		return getGuidanceAccess().getRule();
	}
	
	//Resource returns Resource:
	//    'Resource'
	//    name=EString
	//    '{'
	//        'occuranceNo' occuranceNo=EInt
	//    '}';
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}
	
	//WorkDefinition returns WorkDefinition:
	//    {WorkDefinition}
	//    'WorkDefinition'
	//    name=EString
	//    '{'
	//        ('linksToSuccessors' linksToSuccessors=[WorkSequence|EString])?
	//        ('linksToPredecessors' linksToPredecessors=[WorkSequence|EString])?
	//        ('guidance' '(' guidance+=[Guidance|EString] ( "," guidance+=[Guidance|EString])* ')' )?
	//        ('parameter' '{' parameter+=Parameter ( "," parameter+=Parameter)* '}' )?
	//    '}';
	public WorkDefinitionElements getWorkDefinitionAccess() {
		return pWorkDefinition;
	}
	
	public ParserRule getWorkDefinitionRule() {
		return getWorkDefinitionAccess().getRule();
	}
	
	//enum WorkSequenceType returns WorkSequenceType:
	//                startToStart = 'startToStart' | finishToStart = 'finishToStart' | startToFinish = 'startToFinish' | finishToFinish = 'finishToFinish';
	public WorkSequenceTypeElements getWorkSequenceTypeAccess() {
		return eWorkSequenceType;
	}
	
	public EnumRule getWorkSequenceTypeRule() {
		return getWorkSequenceTypeAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Parameter returns Parameter:
	//    'Parameter'
	//    '{'
	//        'quantity' quantity=EInt
	//        'resource' resource=[Resource|EString]
	//    '}';
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
