/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SimplePDLStandaloneSetup extends SimplePDLStandaloneSetupGenerated {

	public static void doSetup() {
		new SimplePDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
