/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SimplePDLProposalProvider extends AbstractSimplePDLProposalProvider {
}
