/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.simplepdl.parser.antlr.internal.InternalSimplePDLParser;
import org.xtext.simplepdl.services.SimplePDLGrammarAccess;

public class SimplePDLParser extends AbstractAntlrParser {

	@Inject
	private SimplePDLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimplePDLParser createParser(XtextTokenStream stream) {
		return new InternalSimplePDLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Process";
	}

	public SimplePDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimplePDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
