/*
 * generated by Xtext 2.41.0
 */
package org.xtext.simplepdl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimplePDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/simplepdl/parser/antlr/internal/InternalSimplePDL.tokens");
	}
}
