/*
 * generated by Xtext 2.41.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SimplepdlStandaloneSetup extends SimplepdlStandaloneSetupGenerated {

	public static void doSetup() {
		new SimplepdlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
